In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('log_sus.csv', sep=';', header=None, names=["Iterations", "Start-time","Empty", "Description"])
df.drop(columns=['Empty'], inplace=True)
df.head()

    Iterations           Start-time                      Description
0  iteration 1  2023-02-01 08:53:20                     startTestrun
1  iteration 1  2023-02-01 08:53:27                  go to line 100
2  iteration 1  2023-02-01 08:53:32                  toggle comment
3  iteration 1  2023-02-01 08:53:36                    find kconfig
4  iteration 1  2023-02-01 08:53:41  move between searches 6 times

In [3]:
df['Start-time'] = pd.to_datetime(df['Start-time'])
df['End-time'] = df['Start-time'].shift(-1)

In [4]:
df.head()

,Iterations,Start-time,Description,End-time
0,iteration 1,2023-02-01 08:53:20,startTestrun,2023-02-01 08:53:27
1,iteration 1,2023-02-01 08:53:27,go to line 100,2023-02-01 08:53:32
2,iteration 1,2023-02-01 08:53:32,toggle comment,2023-02-01 08:53:36
3,iteration 1,2023-02-01 08:53:36,find kconfig,2023-02-01 08:53:41
4,iteration 1,2023-02-01 08:53:41,move between searches 6 times,2023-02-01 08:53:51

In [5]:
df['Duration(sec)'] = (df['End-time'] - df['Start-time']).dt.total_seconds()
df.head()

,Iterations,Start-time,Description,End-time,Duration(sec)
0,iteration 1,2023-02-01 08:53:20,startTestrun,2023-02-01 08:53:27,7.0
1,iteration 1,2023-02-01 08:53:27,go to line 100,2023-02-01 08:53:32,5.0
2,iteration 1,2023-02-01 08:53:32,toggle comment,2023-02-01 08:53:36,4.0
3,iteration 1,2023-02-01 08:53:36,find kconfig,2023-02-01 08:53:41,5.0
4,iteration 1,2023-02-01 08:53:41,move between searches 6 times,2023-02-01 08:53:51,10.0

In [12]:
df.to_csv('log_sus_duration.csv', sep=';', header=None, index=False)